// this is about page
import React from 'react'
import About from '../components/Aboout'

export const metadata = {
  title: "Hekto Ecommerce about",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
    <About />
    </>
  )
}

export default page