import Footer from "./components/Footer";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import "slick-carousel/slick/slick.css";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400","500","600","700"],
});

export const metadata = {
  title: "Hekto Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefin.className} antialiased`}>
        <Header />
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
